// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://lijf2ukin5gs3n4xsh3j7fdbru.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-5ukaryong5bv7fhyhmj7i3ssei",
    "aws_content_delivery_bucket": "alltube-20181217155931-hostingbucket",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "http://alltube-20181217155931-hostingbucket.s3-website-us-west-2.amazonaws.com"
};


export default awsmobile;
